# Generated by Django 2.2.6 on 2019-11-23 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Adminnistrador', '0002_auto_20191122_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='User name')),
                ('last_name', models.CharField(max_length=150, unique=True, verbose_name='Last name')),
                ('id_card', models.IntegerField(unique=True, verbose_name='C.C')),
                ('address', models.CharField(max_length=150, unique=True, verbose_name='Address')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='E-mail')),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminnistrador.Company')),
                ('phone', models.ForeignKey(max_length=150, on_delete='Phone', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
