# Generated by Django 2.2.6 on 2019-11-23 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminnistrador', '0003_auto_20191123_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='User name')),
                ('last_name', models.CharField(max_length=150, unique=True, verbose_name='Last name')),
                ('id_card', models.IntegerField(unique=True, verbose_name='C.C')),
                ('address', models.CharField(max_length=150, unique=True, verbose_name='Address')),
                ('phone', models.CharField(max_length=150, unique=True, verbose_name='Phone')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='E-mail')),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminnistrador.Company')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.DeleteModel(
            name='User2',
        ),
    ]
